# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f34ba85a71e39b5cabdf33728eeb97dbe07558f476acf3d965ddc8b8a391eaef6db7292379d877d1b3de387abcae69e5ec7ad92c039e482b35d6b479d5a1e068

test:
  secret_key_base: 751a563501bdfce59faac4cb789687956636b25f1ed81a24a506ecc453b671a1f7a937cbb5c9cde1d7ec9f90b2979bde8ab957aecc73de253bb07dc3286f99f5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
